### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by DilumAluthge** [bcbi/ClassImbalance.jl#24]
- [x] ~~Drop support for Julia 0.7 (require Julia 1.0 or greater)~~
- [x] ~~Register and tag version 0.5.0~~
- [x] ~~Get code coverage to 100%~~
- [x] ~~Tell Bors to require both of the CodeCov status checks~~
- [x] ~~Register and tag version 0.6.0~~
- [x] ~~Drop support for Julia 1.0 (require Julia 1.1 or greater)~~
- [x] ~~Register and tag version 0.7.0~~
